version: "3.8"

services:
  php:
    image: php803-apache-ssl-dev
    container_name: '${DOCKER_CONTAINER_NAME}-php'
    restart: unless-stopped
    depends_on:
      - mysql
      - phpmyadmin
    ports:
      - '${HOST_HTTP_PORT:-80}:80'
      - '${HOST_HTTPS_PORT:-443}:443'
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/www/html/logs
      - ./docker/apache/ssl:/var/www/html/ssl
      - ./docker/apache/vhosts.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - network

  mysql:
    image: mysql8-dev
    container_name: '${DOCKER_CONTAINER_NAME}-mysql'
    restart: unless-stopped
    ports:
      - '${HOST_MYSQL_PORT:-3306}:3306'
    volumes:
      - ./dbdata:/var/lib/mysql:delegated
      - ./logs:/var/www/html/logs
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin
    container_name: '${DOCKER_CONTAINER_NAME}-phpmyadmin'
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '${HOST_PHPMYADMIN_HTTP_PORT:-81}:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USERNAME}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /sessions
    networks:
      - network

  npm:
    image: node:15.13
    container_name: '${DOCKER_CONTAINER_NAME}-npm'
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - network
      
networks:
  network: